lib: [
  "_build/install/default/lib/libtrie/META"
  "_build/install/default/lib/libtrie/dune-package"
  "_build/install/default/lib/libtrie/libtrie.a"
  "_build/install/default/lib/libtrie/libtrie.cma"
  "_build/install/default/lib/libtrie/libtrie.cmi"
  "_build/install/default/lib/libtrie/libtrie.cmt"
  "_build/install/default/lib/libtrie/libtrie.cmx"
  "_build/install/default/lib/libtrie/libtrie.cmxa"
  "_build/install/default/lib/libtrie/libtrie.cmxs"
  "_build/install/default/lib/libtrie/libtrie.ml"
  "_build/install/default/lib/libtrie/libtrie__Trie.cmi"
  "_build/install/default/lib/libtrie/libtrie__Trie.cmt"
  "_build/install/default/lib/libtrie/libtrie__Trie.cmti"
  "_build/install/default/lib/libtrie/libtrie__Trie.cmx"
  "_build/install/default/lib/libtrie/opam"
  "_build/install/default/lib/libtrie/trie.ml"
  "_build/install/default/lib/libtrie/trie.mli"
]
doc: [
  "_build/install/default/doc/libtrie/README"
]
